# Generated by Django 6.0.6 on 2026-07-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_systemprompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="voice",
            field=models.CharField(default="longanyang", max_length=50),
        ),
    ]
